### ISSUE TITLE
Private Proxy Authentication

### ISSUE THREAD

**Issue by LeCoupa** [SpookyJS/SpookyJS#100]
Hello,

I just saw #19 and it works great in my case. Any idea on how to authenticate with a private proxy? The following does not work:

```
var spooky = new Spooky({
        child: {
            proxy: '192.128.101.42:9001',
            proxyAuth: 'username:password'
```

In Casper, we just have to do:

```
casperjs --proxy=208.72.118.16:60099 --proxy-auth=username:password proxy.js 
```

**Comment by cod1ingcoding** [comment]
how can I config a specifical type of proxy?
