### ISSUE TITLE
Spooky - Import and use selectXPath

### ISSUE THREAD

**Issue by LeCoupa** [SpookyJS/SpookyJS#109]
How can I import and use the selectXPath function in spooky?

```
var x = require('casper').selectXPath;
```

So as to use it like that:

```
sel = x '//div[@id="myID"]//tr[2]//td[1]//a[contains(@class, "my-class")]'
@click sel
```

It triggers the following errors: (even within the Casper environment)

```
Error: Cannot find module 'casper'
ReferenceError: Can't find variable: x
```

I really need to use xPath as there is currently a bug with nth-child: see [PhantomJS #11632](https://github.com/ariya/phantomjs/issues/11632) & [CasperJS #378](https://github.com/n1k0/casperjs/issues/378)

**Comment by blaiseyuri** [comment]
For anyone looking for a solution to this, here is what I did.

First I went inside the source code and just pulled the selectXPath function
selectXPath =function(expression) {
  return {
    type: "xpath",
    path: expression,
    toString: function() {
      return this.type + " selector: " + this.path;
    }
  };
};

This worked beautifully but the code I'm writing has several steps and for each step you have to redefine the function which makes the code very difficult to read. So I wanted to have the function defined in the node context and then have it passed to the casperJS context through a function tuple.

Problem is you can't pass functions. So I had to use the make the expression a string and then pass it through the tuple, afterwards I would take the string and use the eval function.

Here is my code
```javascript
 // NodeJS/SpookyJS context (they are the same)
selectXPath = 'xPath = function(expression) {
  return {
    type: "xpath",
    path: expression,
    toString: function() {
      return this.type + " selector: " + this.path;
    }
  };
};'

// CasperJS context
// the first two lines of the function are needed for every spooky.then you function you call so is the 
// {x: selectxPath} object
spooky.then([{x: selectXPath}, function() {
    var xPath = null;  
    eval(x);
    return this.sendKeys(xPath('//*[@id="email"]'), 'blaiseyuri@ufl.edu');
  }
]);

```

**Comment by LeCoupa** [comment]
Awesome! Thanks a lot for sharing!
