### ISSUE TITLE
throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by cnaccio** [SpookyJS/SpookyJS#114]
Getting the following error when attempting to run the spooky/examples/hello.js example on Windows 8.1:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)
```

**Comment by hollycoder** [comment]
Thank you

**Comment by arrowing** [comment]
Thank you !!  :+1:

**Comment by smalltalk-josh** [comment]
@cnaccio helped me solved this problem for my environment; he had half the answer I needed
My issue was a combo of file name (cmd fix) and path
see: https://github.com/SpookyJS/SpookyJS/issues/71#issuecomment-267704986
