### ISSUE TITLE
can get it to work on openshift.

### ISSUE THREAD

**Issue by fpena06** [SpookyJS/SpookyJS#138]
Hi,

I cant get spooky to work on openshift. No errors just blank screen.

node examples/hello.js <---- no errors window just stays blank

node --version
v0.10.25

phantomjs --version
1.9.8

casperjs --version
1.1.0-beta3

mocha tests/test/

  the PhantomJS bootstrap script
    ✓ hooks phantom.onError to emit an error event and exit non-zero (292ms)
    ✓ crashes if passed an unknown transport (292ms)

  bootstrap/emit
    ✓ provides emit, which emits an event (70ms)
    1) "before each" hook

  3 passing (1s)
  1 failing

  1) bootstrap/emit "before each" hook:
     Uncaught Error: Child terminated with non-zero exit code 1
      at Spooky.<anonymous> (/var/lib/openshift/5507eca35973caee880000b9/app-root/runtime/dependencies/nodejs/node_modules/spooky/lib/spooky.js:210:17)
      at ChildProcess.EventEmitter.emit (events.js:98:17)
      at Process.ChildProcess._handle.onexit (child_process.js:797:12)

**Comment by fpena06** [comment]
In case it helps someone. Commenting this line completely fixed whatever issues I was having.

        child: {
            //transport: 'http' <---- here
        },

**Comment by GuillaumeLeclerc** [comment]
Thank you :D
