### ISSUE TITLE
I cant get spookyjs to play nicely with socketio.

### ISSUE THREAD

**Issue by fpena06** [SpookyJS/SpookyJS#145]
Has anyone been able to use socketio from within a spooky call? I can send a socketio message fine before I run spooky but whenever I try to send a message inside of spooky.then I get error "Could not serialize request to JSON" when I add spooky.then([{ socket:socket

**Comment by lawnsea** [comment]
Your code example is incomplete, but it looks like you're trying to pass a reference to a SocketIO socket as an argument to `spooky.then`. This definitely won't work. Everything you pass to a spooky method is serialized to JSON and sent to Casper running in a PhantomJS instance.

Please see [the Introduction](https://github.com/SpookyJS/SpookyJS/wiki/Introduction) for details.

**Comment by fpena06** [comment]
Perhaps you can help me with my logic. Here I have this function which for the duration of my scraping emits 'spooky' every 10 seconds. But what if I want to use window.counter to keep a count and emit this count instead? I can do a console log within the scrap and see the value of window.counter but how can I pass its value to another variable outside. I tried declaring myVar=0 and inside of the script set myVar = window.counter but when it gets back to the emit myVar has value 0.

Thanks

(function () {
            var interval = 0,
            intervalId = setInterval(function () {
                socket.emit('chat message', 'spooky');
            }, 10000);
})();

**Comment by lawnsea** [comment]
To send values from Casper to Spooky, use `emit`. You could do something like this:

```javascript
spooky.then(function () {
  var casper = this;
  var count = 0;
  setInterval(function () {
    casper.emit('count', count++);
  }, 10000);
});
```
