### ISSUE TITLE
Disable loading images

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [SpookyJS/SpookyJS#146]
Hello,

I tried to find out but I could not so I decided to ask here. I would like to know if this is possible to disable loading images. I don't need them and it waste a lot of time downloading them.

Thank you very much for your help.

**Comment by lawnsea** [comment]
If this is possible, it will be via an API that PhantomJS exposes.

**Comment by GuillaumeLeclerc** [comment]
It does exposes it but via command line arguments. Is it possible to change the arguments passed to the phantomJs process ?

**Comment by lawnsea** [comment]
You can pass arguments to `casperjs` by adding properties to the `child` property of your config object:

```javascript
var spooky = new Spooky({
        child: {
            transport: 'http',
            foo: 'bar'
        }
    }
```

This will invoke `casperjs` with `--foo=bar`.
