### ISSUE TITLE
hello.js example fails

### ISSUE THREAD

**Issue by johndierks** [SpookyJS/SpookyJS#147]
Hi, I'm trying to get spooky up and running and am getting errors on the example scripts.

Any thoughts on what's not working?

spookyjs 0.2.5
osx: 10.9.5
phantomjs: 1.9.2
casperjs: 1.0.4

I get this error
```
CasperError: __mod_error(/Users/john/dev/<project_dir>/node_modules/spooky/lib/../lib/bootstrap/casper:112):: TypeError: 'undefined' is not an object (evaluating 'requireDirs.forEach')
[ { file: '/Users/john/dev/<project_dir>/node_modules/spooky/lib/../lib/bootstrap/casper.js',
    line: 112,
    function: '_require' },
  { file: '', line: 9, function: 'anonymous' },
  { file: '/usr/local/Cellar/casperjs/1.0.4/libexec/bin/bootstrap.js',
    line: 160,
    function: '_require' },
  { file: '/Users/john/dev/<project_dir>/node_modules/spooky/lib/bootstrap.js',
    line: 54,
    function: '' } ]
{ [Error: Child terminated with non-zero exit code 1] details: { code: 1, signal: null } }
```

**Comment by johndierks** [comment]
✖ 1 of 79 tests failed:

  1) bootstrap/emit "before each" hook:
     Error: Child terminated with non-zero exit code 1
      at Spooky.<anonymous> (/Users/john/Desktop/sandbox/SpookyJS/tests/util/hooks.js:28:19)
      at Spooky.EventEmitter.emit (events.js:95:17)
      at Spooky.<anonymous> (/Users/john/Desktop/sandbox/SpookyJS/lib/spooky.js:216:18)
      at ChildProcess.EventEmitter.emit (events.js:98:17)
      at Process.ChildProcess._handle.onexit (child_process.js:789:12)

**Comment by solick** [comment]
Can you provide more code? from the error only it will be difficult to help. By the way, i would suggest to use the latest supported versions: Phantomjs 1.9.7 and Casperjs 1.1.0

**Comment by johndierks** [comment]
Thank you! I upgraded phantom and casper to the versions you suggested and Spooky no longer crashes.

Though the script then had trouble with Wikipedia's use of SSL. I added the appropriate parameters (as far as I can tell), and submitted a PR: https://github.com/SpookyJS/SpookyJS/pull/150
