### ISSUE TITLE
Sync problem with spooky

### ISSUE THREAD

**Issue by kevinnascimento** [SpookyJS/SpookyJS#155]
I created a service in order to return the result of scrapping, but I'm sync problem. How can I fix this?

Below the code of service that makes the call scrappingHorario function, and after keep hearing result.

```javascript
exports.getClassSchedule = function(user, password) {
    console.log('SCRAPING');
    scrappingHorario();
    
	spooky.on('result', function (res) {
		console.log('SCRAPING RESULT');
	});
	
	console.log('return service');
	return 'test';
}
```

The code below is the function scrappingHorario.

```javascript
spooky.then(function () {
    titleItens = this.evaluate(function () {
        var nodes = document.querySelectorAll('table th');
        return [].map.call(nodes, function(node) {
            return node.outerHTML;
        });
    });

    contentItens = this.evaluate(function () {
        var trNodes = document.querySelectorAll('table tr');
        itens = [].map.call(trNodes, function(trNode) {
            tdNodes = trNode.querySelectorAll('td');
            return [].map.call(tdNodes, function(tdNode) {
                return tdNode.textContent;
            });
        });
        return itens;
    });

    var result = {
    	'title' : titleItens,
    	'content' : contentItens
    };

    this.emit('result', result);
});

spooky.run();

```
Result:
![screen shot 2015-07-31 at 12 28 23 pm](https://cloud.githubusercontent.com/assets/5147127/9010812/ade3f530-377f-11e5-9912-d88a1a5c9676.png)

**Comment by pedro93** [comment]
I dont think this is a spooky problem, its how Javascript works. When you call the getClassSchedule function, it will execute all code in it but wont wait for async calls(your scrappingHorario function has them, the "then functions"). I would sugest using q promises, with that in mind, what you could do to have the correct console logs is:

```javascript
var Q = require('q');

exports.getClassSchedule = function(user, password) {
   var deferred = Q.defer();

    console.log('SCRAPING');
    scrappingHorario();

    spooky.on('result', function (res) {
        console.log('SCRAPING RESULT');
    });

   spooky.then(function(){ //code called after the above spooky.on
    console.log('return service');
   deferred.resolve('test');
   });
 return deferred.promise;
}
```
This code would then have to be called like this:
```javascript
getClassSchedule(user,password).then(function(result){
//do stuff with result variable
});
```
Hope that makes sense

**Comment by kevinnascimento** [comment]
I thank you.

One more question, let me know if you know a library for .then() function is necessary?

**Comment by pedro93** [comment]
the q library offers the then functionality you need (check out the github: https://github.com/kriskowal/q) , just not sure getClassSchedule function is in the node or spooky enviroment. If its in the latter then q promises wont work.

**Comment by solick** [comment]
@kevinnascimento i´m closing the issue because your question seemed to be answered.

**Comment by kevinnascimento** [comment]
I used sockets for this problem.

Thank you @pedro93
