### ISSUE TITLE
Controlling and Preventing Page Cache

### ISSUE THREAD

**Issue by smasher164** [SpookyJS/SpookyJS#157]
It seems that either PhantomJS is keeping a browser cache of the page after one successful load. This makes debugging impossible when testing DOM manipulation, since I have to wait for the cache to clear, or else the modified DOM values aren't retrievable. 

It isn't fixed in the 2.0.0 release of PhantomJS, and although the CasperJS `clear()` method doesn't apply to this case, the PhantomJS documentation tells us to do a `page.clearMemoryCache()`. But in order to do that, I'd need the page module, which I can get from `casper.page.pageModuleApi()`, however, I'm not at ll sure how to retrieve this reference through Spooky.

Is this the correct way to prevent page cache? Is it even possible through Spooky?

**Comment by lawnsea** [comment]
The CasperJS instance is available as `this` in a `then` callback:

```javascript
spooky.then(function () {
  this.page.pageModuleApi().clearMemoryCache();
});
```

**Comment by smasher164** [comment]
Resolved. Thank You.

**Comment by smasher164** [comment]
Actually, this function appears to be `undefined`. Is this the correct way to clear cache with Spooky? I'm getting this `TypeError`.

```javascript
TypeError: 'undefined' is not a function (evaluating 'this.page.pageModuleApi()')
[ { file: '', line: 3, function: '' },
  { file: '/usr/local/Cellar/casperjs/1.1-beta3/libexec/modules/casper.js',
    line: 1553,
    function: 'runStep' },
  { file: '/usr/local/Cellar/casperjs/1.1-beta3/libexec/modules/casper.js',
    line: 399,
    function: 'checkStep' } ]
TypeError: 'undefined' is not a function (evaluating 'this.page.pageModuleApi()')
  /Users/username/Projects/spookyproject:3
  /usr/local/Cellar/casperjs/1.1-beta3/libexec/modules/casper.js:1553 in runStep
  /usr/local/Cellar/casperjs/1.1-beta3/libexec/modules/casper.js:399 in checkStep
{ [Error: Child terminated with non-zero exit code 1] details: { code: 1, signal: null } }
```

**Comment by lawnsea** [comment]
In that callback, `this` is the CasperJS instance returned by calling `casper.create`, so this is not a Spooky problem. According to [CasperJS's documentation](http://docs.casperjs.org/en/latest/faq.html#how-do-i-use-phantomjs-page-module-api-in-casperjs), that method should be defined once `start` is called.

**Comment by Dan347** [comment]
I'm having a similar issue. I go to a page, write in a text box, press a button, then retrieve a value.

I then want to go to the page state before the button was pressed. Unfortunately, even when I do this.open for the url, I can see that the html is in the same state as if I had pressed the button. I have tried spooky.destroy and other approaches too, but nothing has worked.

**Comment by lawnsea** [comment]
AFAICT, this is a bug in Casper or Phantom. Closing.

**Comment by natsu90** [comment]
Anyone get this working?
