### ISSUE TITLE
Spookyjs Example Won't run

### ISSUE THREAD

**Issue by MDJCL** [SpookyJS/SpookyJS#169]
Whenever I run any spookyjs program (including hello.js in the example) it returns

     {
         id: 1,
         code: -32603,
         message: '\'undefined\' is not a function (evaluating \'fs.isWindows()\')'
     } {
         id: 2,
         code: -32603,
         message: 'Casper is not started, can\'t execute `then()`'
     } {
         id: 3,
         code: -32603,
         message: 'Casper is not started, can\'t execute `run()`'
     }

I reinstalled using npm multiple times

Thanks!

**Comment by pedro93** [comment]
Could you please post your computer's OS system specs and software versions you are using to run spooky (node, phantom, casper)?

**Comment by MDJCL** [comment]
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty

I tried to get npm to install phantomjs 1.9.15, 1.1.0-beta3 . Am I missing a way to tell spooky the path to look for?

**Comment by pedro93** [comment]
Check if phantom and casperjs are in the path of your OS please. If that is the case, spooky should currently call these external programs

**Comment by MDJCL** [comment]
As far as I can tell, they are. Calling phantomjs and casperjs from the terminal works find and they are in the `PATH` variable

**Comment by solick** [comment]
@MDJCL can you please post the results of node --version, phantomjs --version and casperjs --version?

**Comment by MDJCL** [comment]
Sure (and thanks for helping me)
node: `v0.12.4`
phantomjs: `1.9.7`
casperjs: `1.1.0-beta3`

**Comment by solick** [comment]
@MDJCL you´re welcome. For me it looks like fs is not found. Unfortunately i will not have time this week to check your configuration. Are you sure you installed phantomjs and casperjs globally (using npm -g)?

**Comment by MDJCL** [comment]
That worked perfectly, I had an odd phantomjs setup that worked but now even spooky works. Thanks so much

**Comment by solick** [comment]
Great to hear that you solved your problem. I close the issue now.
