### ISSUE TITLE
SpookyJS still under active development?

### ISSUE THREAD

**Issue by sawteeth** [SpookyJS/SpookyJS#170]
I get an error just running `spooky.start();` -- undefined function...

**Comment by sawteeth** [comment]
Does everything spooky does have to be in the `new Spooky` object?

**Comment by solick** [comment]
yes and no. You need to have a spooky onstance to work with but you can pass result via the emit function outside the spooky object and process the results there.

**Comment by sawteeth** [comment]
@solick cool.  Can you give me an example on how to do that?

**Comment by sawteeth** [comment]
Because I copy and pasted my whole CasperJS script into `new Spooky();`.

**Comment by pedro93** [comment]
Have you tried the example provided in the repository (file hello.js)? the spooky.on functions allow you to deal with results outside the new spooky object function.

**Comment by sawteeth** [comment]
Ok -- but you can't use `spooky.start()` outside of `new Spook();`?

**Comment by lawnsea** [comment]
> Because I copy and pasted my whole CasperJS script into new Spooky();.

That definitely won't work. Please take a look at the example script.

**Comment by sawteeth** [comment]
@lawnsea the example script really doesn't have much functionality though... It's basically just getting a page title...

**Comment by solick** [comment]
You cannot coppy-paste your casperjs script because spookyjs does not support all functions of casperjs. As pedro93 said, you have to emit inside your spooky instance and pass variables / objects through the event which can than be catched and processed outside.

**Comment by solick** [comment]
@sawteeth a basic example could look like this:

    var spooky = new spooky({...}, function(err) {
         ...
        /* do something */
        spooky.run(function() {
           this.emit("finalResult", yourFinalResult); 
     });
    });

    spooky.on("finalResult", function(yourFinalResult) {
        /* do something with your final result */
    });

**Comment by sawteeth** [comment]
@solick thanks.  Are there docs that flesh out the available methods?

**Comment by solick** [comment]
Not a direct document but you can get all provided document out of this file: https://github.com/SpookyJS/SpookyJS/blob/master/lib/bootstrap/casper.js we are evluation at the moment which functions we could additionally provide and also work in the documentation.
