### ISSUE TITLE
Passing JSON object from nodejs to casper.

### ISSUE THREAD

**Issue by Kuwshi** [SpookyJS/SpookyJS#174]
Hi everyone, I'm trying to access nodejs request body, that is a JSON object, in spooky. I know about function tuples but it seems to work only for simple variables (string, int, etc).

```javascript
spooky.then([{

            simpleInt : 3,
            simpleStr : "Scary !",
            jsonO : req.body  //nodejs express

        }, function(){

          // Here I have access to simpleInt, simpleStr but jsonO is undefined

        }
]);
```

Am I doing something wrong ? Should I cheat and use events to grab the informations I need ? Thanks !

Edit : I also tried to build an array with the json Object but I get the same result, or, the lack of result if you will.

**Comment by solick** [comment]
Try to Stringify the req.body and then rebuild the JSON object internally

**Comment by Kuwshi** [comment]
This is exactly the way to go !

I feel now that this was a stupid question. I'm fairly new to nodejs, javascript in general. I guess I was overwhelmed by that and the fact that I do have 3 javascript environment in not even 100 lines of code.

Thanks for the very quick reply. :+1: 

To those reading this later, here what it looks like now :

```javascript
try {
    var Spooky = require('spooky');
} catch (e) {
    var Spooky = require('../lib/spooky');
}
exports.search = function (req, res) {

    var spooky;

    spooky = new Spooky({
        child: {
            transport: 'http'
        },
        casper: {
            pageSettings: {
                userAgent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:39.0) Gecko/20100101 Firefox/39.0',
                loadImages: false,
                loadPlugins: false   
            },
            logLevel: 'debug',
            verbose: true
        }
    }, function (err) {

        var fs = require('fs');

        if (err) {
            e = new Error('Failed to initialize SpookyJS');
            e.details = err;
            throw e;
        }
        
        spooky.start('http://www.github.com');

        spooky.then([{

            bodyStr : JSON.stringify(req.body)

        }, function (){

            var myObject = JSON.parse(bodyStr);
            this.emit('console', myObject.access.to.whatever);

        }]);

        spooky.run();

    });

};
```

**Comment by solick** [comment]
Great to see that it worked for you. I now close the issue.
