### ISSUE TITLE
Show HTTP Headers? 

### ISSUE THREAD

**Issue by iavasquez** [SpookyJS/SpookyJS#176]
I have a site that is behaving differently when I interact with in in a traditional browser versus spooky/casper/phantom.  I would like to debug by printing out the entire http header requests and responses to the console or a file to see what is different between my browser and the phantom browser (similar to how I would using developer tools on the browser).  How can I get all http request / response including headers in a spooky event handler?

**Comment by lawnsea** [comment]
Your `then` handlers have access to [the CasperJS instance](http://docs.casperjs.org/en/latest/modules/casper.html#the-casper-class) as `this`. See the Casper and Phantom docs.
