### ISSUE TITLE
Casperjs ENOENT

### ISSUE THREAD

**Issue by jordanfan20** [SpookyJS/SpookyJS#177]
I've cloned the repository onto my computer but everytime I try to run the example "hello world" I get the following error,
"Error: spqn casperjs ENOENT."

Any thoughts?

**Comment by pedro93** [comment]
Please refer to this issue https://github.com/SpookyJS/SpookyJS/issues/71

**Comment by jordanfan20** [comment]
@pedro93 I've tried the few suggestions mentioned. I first installed casper globally. This didn't work, I then tried issue #131 and changed, 

"child: {
        command: 'casperjs' + (process.platform === 'win32' ? '.cmd' : '')" 

This however just led to another error. 

"Error: Child terminated with non-zero exit code 1"

**Comment by pedro93** [comment]
@jordanfan20 We will look into this, in the mean time if you would like to try, checkout the gruntTesting branch and attempt to run it again. I've tried a few windows related modifications there.

**Comment by jordanfan20** [comment]
@pedro93 Thanks for the share. When trying out "gruntTesting" I also ran into the,

"Error: Child terminated with non-zero exit code 1",

but when I installed phantom globally it resolved the issue. It also resolved the issue on the main version. 

Thanks again :)

**Comment by pedro93** [comment]
@jordanfan20 Sure thing I am sorry the code is not yet working out of the box. I will now close the issue.

**Comment by retargetly** [comment]
I'm on Ubuntu 14.04, and after installing casperjs globally I still had another issue ([Error: Child terminated with non-zero exit code 1]), so the solution is installing phantomjs globally as well:

sudo npm install -g casperjs
sudo npm install -g phantomjs

Then the spooky example works without problem, the output:
"Hello, from Spooky the Tuff Little Ghost - Wikipedia, the free encyclopedia"
