### ISSUE TITLE
Error Handling in SpookyJS

### ISSUE THREAD

**Issue by Kuwshi** [SpookyJS/SpookyJS#178]
Hi everyone, first of all, I am not sure where to post this exactly. This is definitely not an issue, more like an open discussion on a good practice. I could not find a proper place where post this, so, if there is a group of some sort or a forum, please, tell me and I will move the discussion over there.

That being said, let's get to business.

I have my NodeJS server running, using Express and the requests are routed and dispatched to the right SpookyJS  script to be executed. From there, I would like to handle errors correctly to stop the SpookyJS / CasperJS execution and not crash my node server. I've went through both SpookyJS and CasperJS documentation but I am still unsure on how I should handle the situation.

If you are short on time, please, do not go with the biggest and detailed answer, just point me a direction. Thank you !

**Comment by pedro93** [comment]
Correct me if im wrong, you want the SpookyJS process to self-terminate if it catches an error? You can always return a special value which signals a SIGKILL of sorts to the NodeJS app

**Comment by Kuwshi** [comment]
Yes, this is what I want. Basically, my question was : what is the proper way to kill a SpookyJS process on errors ?

**Comment by Kuwshi** [comment]
Because right now, when I want to exit, I use an event emitter which send a response with Express. But, when I try using spooky.die() or spooky.exit() the spooky process continues and makes my nodejs crash because it can not handle the errors that will occur.

**Comment by Kuwshi** [comment]
Okay I'm just an idiot. I was trying to self exit in the event scope, which is the nodeJS scope. Now I just call the event that does what I want node side and die, in the spooky scope, after the event call.

I am really sorry for the waste of your time, pedro93 and other gentlemen who took time to read this post. I mean, I do understand the different javascript environments concept but... I guess I was tired.

Still, quick question aside, @pedro93 , Where would you like to receive these type of questions ? Here is fine, we have a google group, keep them on Stackoverflow ?

Thanks.

**Comment by pedro93** [comment]
I am glad you managed to find the solution yourself. This platform is mostly about issues whilst running your code. If you are unsure how to code a certain thing please post on StackOverflow or on our gitter chat: https://gitter.im/SpookyJS/SpookyJS
I will now close this issue
