### ISSUE TITLE
returning from spooky 

### ISSUE THREAD

**Issue by MVMS1994** [SpookyJS/SpookyJS#186]
How to retrieve the control from spooky? I tried exit() and destroy(). But the url gets changed to blank whereas the control is still inside spooky. For eg:

fun1 = deaync(function() {
console.log("in part1")
var url = "https://www.google.com";
spooky.start(url);
spooky.then(function () {
}
spooky.run();
spooky.on('run.complete' , function(){
this.exit();
spooky.destroy();
});

console.log("before spooky");
fun1();
console.log("after spooky")

In this example "after spooky doest get printed since the control is still in spooky

**Comment by lawnsea** [comment]
I would expect to see the following:

```
before spooky
in part 1
after spooky
```

However, I have no idea what `deaync` does.

**Comment by MVMS1994** [comment]
I have a global variable x=5.
How to check for the value of x every 1 second for any change?

**Comment by solick** [comment]
Checking a value for a change is no bug in spookyjs but basic knowledge of javascript. Please consult some books or intruductions to javaascript / nodejs.
