### ISSUE TITLE
passing values between then and emit 

### ISSUE THREAD

**Issue by MVMS1994** [SpookyJS/SpookyJS#188]
spooky.start("www.example.com");
spooky.then( function() {
      this.flag = false;
     this.emit('find');
}
spooky.run();

spooky.on('find' , function() {
console.log(this.flag) //it shows undefined
}

**Comment by solick** [comment]
No, you have to pass the value with the emit function:

this.emit('find', flag);

and then:

spooky.on('find', function(myflag) {
console.log(myflag); }

another way would be to save your variable within the window object and catch it in the run function:

spooky.start("www.example.gom);
spooky.then(function() {

window.myVar = false;
}

spooky.run(function() {

var myVar = window.myVar;

this.emit('finalResult', myVar);
}

spooky.on('finalResult', function(myVar) {

console.log(myVar);

}

**Comment by MVMS1994** [comment]
But if I change the value in emit function it must get detected in the then function.... This is for making an asynchronous call in emit and get the return value. The spooky should wait till the value is returned.

**Comment by solick** [comment]
This is not a good idea because you would create highly interdependent code. You should re-think your concept. Please note that this is an issue system, to discuss your concept and ask general questions on software please use stackoverflow or gitter.
