### ISSUE TITLE
spookyjs data access

### ISSUE THREAD

**Issue by MVMS1994** [SpookyJS/SpookyJS#189]
spooky.flag = true;
spooky.start("www.sample.com");
spooky.then(function() {
console.log(spooky.flag); // url changes to about:blank
});

If I try to access spooky.flag inside then function, the url is getting changed to blank. How to access this variable inside then function?

**Comment by solick** [comment]
Please re-think your concept, this is not a good idea. As said in #188 you should propose your concept at gitter or stackoverflow
