### ISSUE TITLE
injection

### ISSUE THREAD

**Issue by Suhsmitha19** [SpookyJS/SpookyJS#191]
try {
    var Spooky = require('spooky');
} catch (e) {
    var Spooky = require('../lib/spooky');
}

var spooky = new Spooky({
    child: {
        transport: 'http'
    },
    casper: {
        logLevel: 'debug',
        verbose: true,
        clientScripts: ["abc.js"]
    }
}, function (err) {
    if (err) {
        e = new Error('Failed to initialize SpookyJS');
        e.details = err;
        throw e;
    }

    spooky.start("http://www.google.com");

    spooky.then(function(){
        this.evaluate(function() {
            console.log("testing");
            //var x = punycode.encode("hi");
            console.log("x: "+x);
        });
    });

    spooky.run();
});

When I run this I get a warning:

warning] [phantom] Failed injecting abc.js client side
⚠  Failed injecting abc.js client side

**Comment by pburtchaell** [comment]
This is a duplicate issue. You should close it @Suhsmitha19.
