### ISSUE TITLE
tiny-jsonrpc not found

### ISSUE THREAD

**Issue by pelallemant** [SpookyJS/SpookyJS#195]
Hi,

I had to run `npm install tiny-jsonrpc --save` in order to make spooky work.

If you just install phantomjs-prebuilt, casperjs and spookyjs you get the error:

```
Error: Cannot find module '/home/xxxxxxxx/node_modules/spooky/lib/../node_modules/tiny-jsonrpc/lib/tiny-jsonrpc'
[ { file: 'phantomjs://platform/bootstrap.js',
    line: 299,
    function: 'require' },
  { file: 'phantomjs://platform/bootstrap.js',
    line: 263,
    function: 'require' },
  { file: 'phantomjs://platform/http-server.js',
    line: 6,
    function: '' } ]
{ [Error: Child terminated with non-zero exit code 1] details: { code: 1, signal: null } }
```

Best regards

**Comment by Velissel** [comment]
I was having the same issue, and I guess you are using npm >= 3.0 which tries to install depenecies as flat as possible. My solution is to copy tiny-jsonrpc module in node_modules to node_modules/spooky/node_modules

**Comment by pelallemant** [comment]
@Velissel : Thanks for the answer but in fact just doing `npm install tiny-jsonrpc --save` solves the problem :) 
I'm expecting one maintainer to add tiny-jsonrpc in the package.json .

**Comment by slavafomin** [comment]
Hello! I'm having the same issue.

**Comment by lawnsea** [comment]
@Velissel is correct, this is due to spooky not playing nicely with npm 3. See #175.

> I'm expecting one maintainer to add tiny-jsonrpc in the package.json
https://github.com/SpookyJS/SpookyJS/blob/master/package.json#L17
