### ISSUE TITLE
Error : TypeError: Cannot read property 'setEncoding' of null

### ISSUE THREAD

**Issue by godzillad** [SpookyJS/SpookyJS#205]
I am getting this error. 
Here is my setup:
OS : Oracle linux 7
node : 4.4.5
phantomjs : 2.1.1
casperjs : 1.1.1

Stack : 

TypeError: Cannot read property 'setEncoding' of null
    at Spooky._spawnChild (/home/xxxuser/node_modules/spooky/lib/spooky.js:193:11)
    at new Spooky (/home/xxxuser/node_modules/spooky/lib/spooky.js:116:22)
    at onQuery (/home/xxxuser/data_service_flight.js:100:15)
    at Layer.handle [as handle_request](/home/xxxuser/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/xxxuser/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/xxxuser/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request](/home/xxxuser/node_modules/express/lib/router/layer.js:95:5)
    at /home/xxxuser/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/home/xxxuser/node_modules/express/lib/router/index.js:330:12)
    at next (/home/xxxuser/node_modules/express/lib/router/index.js:271:10)

**Comment by pelallemant** [comment]
How do you produce that error ? example code ?

**Comment by godzillad** [comment]
Here's the code.

```
'use strict';
var express = require('express');
var http = require('http');
var htmlparser = require("htmlparser2");
var Spooky = require('spooky');

var ip_addr = '0.0.0.0';
var port    =  '8888';

var app = express('Test');
app.get('/data', onQuery);

var server = app.listen(port ,ip_addr, function(){
    console.log('Listening at :' + server.address().port);
});

function onQuery(req, res , next){

        console.log("#Request Recieved#");
        var spooky = new Spooky({

                child: {
                        spawnOptions : { stdio: 'inherit'}
                },

                casper: {
                    pageSettings: {
                        loadImages:  false
                    }
                }    
        }, function (err) {
                if (err) {

                    console.log('Failed to initialize SpookyJS');
                    e = new Error('Failed to initialize SpookyJS');
                                        e.details = err;
                    throw e;
                }
                console.log('starting SpookyJS');
                spooky.start("http://anyURL.com");
                // Removed some code here  ....
                // Basically, I am doing spooky.waitFor a tag and then emit a 'gotData' event
                spooky.run();
        });

        spooky.on('error', function (e, stack) {
                console.log("Error in spooky : " + e);
                console.log(stack);
                throw e;
        });
        //I am emitting this event from code I removed above
        spooky.on('gotData', function (response) {
                console.log(response);
                parseAndRespond(response);
        });
        function parseAndRespond(response){
                console.log('Parsing...');
                 res.send(200, "OK");
        }
}
```

**Comment by pedro93** [comment]
Could you explain a bit what you are trying to do? I find it hard to understand this snippet of code.
Please could you highlight the line in which the code broke in this snippet?

**Comment by godzillad** [comment]
This is standard javascript code! This is how you need to write code for node js! and thats not an error handler!  I guess, this error might be because of various versions of dependent libraries that might be clashing.
