### ISSUE TITLE
Error code 32603 - fs.isWindows()

### ISSUE THREAD

**Issue by edoardo-conti** [SpookyJS/SpookyJS#207]
Hi, I get this message when i try to use spooky on my app.js : 

`
I'm 'fs' modules
{ id: 1,
  code: -32603,
  message: 'undefined is not a function (evaluating \'fs.isWindows()\')' }
{ id: 2, code: -32603, message: 'Type error' }
{ id: 3, code: -32603, message: 'Type error' }
{ id: 4, code: -32603, message: 'Type error' }
{ id: 5, code: -32603, message: 'Type error' }
{ id: 6, code: -32603, message: 'Type error' }
{ id: 7, code: -32603, message: 'Type error' }`

My current configuration ( AWS ubuntu 14.04 ) : 
_node: v5.7.0
casperjs: 1.1.1
phantomjs: 2.1.1_

Thanks.

**Comment by edoardo-conti** [comment]
Fixed by deleting the folder _node_modules/fs_ .

**Comment by Dindaleon** [comment]
What if I need that module for my app?
