### ISSUE TITLE
Error: Child terminated with non-zero exit code 1

### ISSUE THREAD

**Issue by ucarbehlul** [SpookyJS/SpookyJS#73]
When I try to use spooky with node command I encounter this error message:

``` events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Child terminated with non-zero exit code 1
    at Spooky.<anonymous> (/Users/baysungur/dev/gtranslate_scaper/node_modules/spooky/lib/spooky.js:177:17)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:789:12)
```

My configuration is as follows:

```
transport: {
            http: {
                host: 'localhost',
            }
        },    
    casper: {
        logLevel: 'debug',
        verbose: true,
    },
    child: {
        command: 'casperjs',
        port: 8081,
        script: './node_modules/spooky/lib/bootstrap.js',
        spooky_lib: './node_modules/spooky/',
        transport: 'stdio',
        bufferSize: 16 * 1024 // 16KB
    } 
```

when I added `console.log(options.command, args.join(' ') )` to spawning code, I got this:
`casperjs ./node_modules/spooky/lib/bootstrap.js --command=casperjs --port=8081 --spooky_lib=./node_modules/spooky/ --transport=stdio --bufferSize=16384`

So I tried running it and I got this error:
`{"jsonrpc":"2.0","method":"emit","params":["error","CasperError: Can't find module ./node_modules/spooky/lib/bootstrap/emit",[{"file":"/usr/local/Cellar/casperjs/1/libexec/bin/bootstrap.js","line":214,"function":"patchedRequire"},{"file":"./node_modules/spooky/lib/bootstrap.js","line":18,"function":""}]]}`

If I replace . with `pwd` in the command, namely `casperjs`pwd`/node_modules/spooky/lib/bootstrap.js --command=casperjs --port=8081 --spooky_lib=`pwd`/node_modules/spooky/ --transport=stdio --bufferSize=16384`, this time I got this error:
`{"jsonrpc":"2.0","method":"emit","params":["error","Error: Cannot find module 'events'",[{"file":"phantomjs://bootstrap.js","line":289,"function":""},{"file":"phantomjs://bootstrap.js","line":254,"function":"require"},{"file":"/Users/baysungur/dev/gtranslate_scaper/node_modules/spooky/lib/stream.js","line":28,"function":""},{"file":"/Users/baysungur/dev/gtranslate_scaper/node_modules/spooky/lib/stream.js","line":142,"function":""},{"file":"/Users/baysungur/dev/gtranslate_scaper/node_modules/spooky/lib/stream.js","line":143,"function":""}]]}`

I installed 1.1.0-DEV version of casperjs with brew and phantomjs (version 1.9.1) with brew as well. I installed Spooky with npm to the working directory.

It works with the stable version of casperjs but 1.1.0-DEV does not work. The reason I'm trying DEV is that xpath seems to work better in it.

Best Regards

**Comment by danielkalen** [comment]
#74
