### ISSUE TITLE
Is there a way to pass arguments to Casper.js?

### ISSUE THREAD

**Issue by arloduff** [SpookyJS/SpookyJS#81]
I've been looking through the documentation, but haven't seen any way of doing this. I need to pass the --ignore-ssl-errors=yes parameter to Casper/Phantom. I've tried placing the parameter in the command field of the child object when Spooky is initiated, e.g.

```
var Spooky = require("spooky");

  this.spooky = new Spooky({
  capser: {
    logLevel: "debug",
    verbose: true
  },
    child: {
      command: "./casperjs/bin/casperjs --ignore-ssl-errors=yes",
 ...
```

but this hasn't worked.

Is there any functionality that would enable me to do this?

**Comment by btiwaree** [comment]
I am using both http and https (https since I use a form submit), I have something like:            
        child: {
           transport: 'http',
           }

and

            "ignore-ssl-errors": true,
            "ssl-protocol": "tlsv1"

enabled as well.
I get:
submitting form to /some-url, HTTP POST
unable to submit form

Any help will be appreciated.
