### ISSUE TITLE
Global Variable and External functions in SpookyJS

### ISSUE THREAD

**Issue by lerio** [SpookyJS/SpookyJS#99]
I'm new to SpookyJS/CasperJS and I'm trying to figure out the execution flow.
This is what I'm trying to achieve:

1) load a page
2) store an image of the page
3) pass this image to a function and execute it (this process is quite long: ~15 seconds)
4) wait for the function to return the result
5) use the returned value to fill a field in the form in the loaded page
6) submit the form

this is a code snippet which tries to explain the solution I came up with:

``` javascript
var globProcessedImage = 'empty';

try {
    var Spooky = require('spooky');
} catch (e) {
    var Spooky = require('../lib/spooky');
}

var spooky = new Spooky({
    child: {
        transport: 'http'
    },
    casper: {
        logLevel: 'debug',
        verbose: true
    }
}, function (err) {
    if (err) {
        e = new Error('Failed to initialize SpookyJS');
        e.details = err;
        throw e;
    }

    spooky.start('http://example.com');

    spooky.then(function() {
        this.captureSelector('./image.png', '#img-node');
    });

    spooky.waitFor([{spookyGlobProcessedImage: globProcessedImage}, function() {
        this.emit('image.processed');
        return spookyGlobProcessedImage !== 'empty';
    }], [{spookyGlobProcessedImage: globProcessedImage}, function then() {
        this.sendKeys('#input_field', spookyGlobProcessedImage);
    }]);

    spooky.then(function() {
        this.capture('./page.png');
    });

    spooky.run();

    spooky.on('image.processed', function() {
        setTimeout(function() {
            globProcessedImage = 'my_long_awaited_result';
        }, 15000);
    });
});

spooky.on('error', function (e, stack) {
    console.error(e);

    if (stack) {
        console.log(stack);
    }
});

/*
 // Uncomment this block to see all of the things Casper has to say.
 // There are a lot.
 // He has opinions.
 spooky.on('console', function (line) {
 console.log(line);
 });
 */

spooky.on('log', function (log) {
    if (log.space === 'remote') {
        console.log(log.message.replace(/ \- .*/, ''));
    }
});
```

Looks like `spooky.waitFor` is not able to find `spookyGlobProcessedImage` : `ReferenceError: Can't find variable: spookyGlobProcessedImage`

**Comment by zixia** [comment]
is there anyway to check global variable in " spooky.waitFor"?

**Comment by solick** [comment]
@zixia global within which scope? You can gave a global javascript variable, a global spookyjs variable, a global casperjs variable.

You can do the following:

    var myGlobalVar = "something";
    var spooky = new Spooky({
       ... 
      }, function(err) {
        spooky.start(url);
       spooky.then([{myGV: myGlobalVar}, function() {
      window.myGlobalVar = myGV;
     }]);

    spooky.then(function() {
     //do something with window.myGlobalVar
    });

    spooky.run(function() {
    //after you saved all your results within window.myGlobalVar
    this.emit("finalResult", window.myGlobalVar);
    
     this.exit();
     });
     
     });
         
         
     spooky.on("finalResult, function(result) {
        myGlobalVar = result;
       });

**Comment by iavasquez** [comment]
@lerio Did you ever come up with a solution for this use case with Spooky/Casper or any alternative technology?  

I have this exact same use case and am trying to figure out the best approach right now.  

Right now, I assume I could 1) download the image to the local drive, 2) emit an event with the filepath of the image 3) manually force Spooky/Casper to wait for a fixed amount of time that should exceed how long the other webservice takes 4) let the web service return its results 5) pass the result of that webservice into the next casper .then() method.  

However, I would like a more elegant solution that waits for the external webservice to return results then fire the next step in the Casper process.  Any help is appreciated.
